'use client'
import { useEffect, useState } from 'react'
import { LogIn, LogOut, Package, Store, Truck, CheckCircle2, Clock } from 'lucide-react'

type Data = { partner: any; orders: any[] }
const rupiah = (n:number) => new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n)
const statusIcon:any = { menunggu: Clock, diproses: Package, dikirim: Truck, selesai: CheckCircle2 }

export default function MitraPage(){
 const [data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('')
 const [kodeMitra,setKode]=useState(''),[pin,setPin]=useState(''),[busy,setBusy]=useState(false)
 const load=async()=>{setLoading(true);const r=await fetch('/api/mitra/me',{cache:'no-store'});if(r.ok)setData(await r.json());else setData(null);setLoading(false)}
 useEffect(()=>{load()},[])
 const login=async(e:any)=>{e.preventDefault();setBusy(true);setError('');const r=await fetch('/api/mitra/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kodeMitra,pin})});const j=await r.json();if(!r.ok)setError(j.error||'Login gagal');else await load();setBusy(false)}
 const logout=async()=>{await fetch('/api/mitra/logout',{method:'POST'});setData(null);setPin('')}
 if(loading)return <main className="min-h-screen bg-slate-50 flex items-center justify-center">Memuat...</main>
 if(!data)return <main className="min-h-screen bg-slate-50 flex items-center justify-center p-4"><div className="w-full max-w-md bg-white rounded-3xl shadow-xl border p-8"><div className="flex justify-center mb-5"><div className="h-16 w-16 rounded-2xl bg-emerald-600 text-white flex items-center justify-center"><Store size={32}/></div></div><h1 className="text-2xl font-bold text-center">Login Mitra</h1><p className="text-slate-500 text-center mt-2 mb-7">JAGAD STOCKIS • Portal Mitra</p><form onSubmit={login} className="space-y-4"><div><label className="text-sm font-medium">Kode Mitra</label><input value={kodeMitra} onChange={e=>setKode(e.target.value.toUpperCase())} placeholder="Contoh: JGD-001" className="mt-1 w-full rounded-xl border px-4 py-3 outline-none focus:ring-2 focus:ring-emerald-500" required/></div><div><label className="text-sm font-medium">PIN</label><input value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,'').slice(0,8))} type="password" inputMode="numeric" placeholder="Masukkan PIN" className="mt-1 w-full rounded-xl border px-4 py-3 outline-none focus:ring-2 focus:ring-emerald-500" required/></div>{error&&<p className="text-sm text-red-600 bg-red-50 p-3 rounded-xl">{error}</p>}<button disabled={busy} className="w-full rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-semibold py-3 flex justify-center gap-2"><LogIn size={20}/>{busy?'Memeriksa...':'Masuk sebagai Mitra'}</button></form></div></main>
 const total=data.orders.reduce((s,o)=>s+o.totalHarga,0)
 return <main className="min-h-screen bg-slate-50"><header className="bg-white border-b"><div className="max-w-6xl mx-auto p-4 flex items-center justify-between"><div><p className="text-xs font-semibold text-emerald-600">JAGAD STOCKIS</p><h1 className="font-bold text-xl">Dashboard Mitra</h1></div><button onClick={logout} className="border rounded-xl px-4 py-2 flex gap-2 items-center"><LogOut size={17}/>Keluar</button></div></header><div className="max-w-6xl mx-auto p-4 md:p-6"><section className="bg-emerald-700 text-white rounded-3xl p-6 mb-6"><p className="text-emerald-100">Selamat datang, {data.partner.namaPic}</p><h2 className="text-2xl font-bold mt-1">{data.partner.namaCabang}</h2><p className="mt-2 text-sm text-emerald-100">{data.partner.kodeMitra} • {data.partner.whatsapp}</p></section><div className="grid grid-cols-2 md:grid-cols-3 gap-4 mb-6"><div className="bg-white border rounded-2xl p-5"><p className="text-sm text-slate-500">Total Pesanan</p><p className="text-2xl font-bold mt-1">{data.orders.length}</p></div><div className="bg-white border rounded-2xl p-5"><p className="text-sm text-slate-500">Total Belanja</p><p className="text-xl font-bold mt-1">{rupiah(total)}</p></div><div className="bg-white border rounded-2xl p-5 col-span-2 md:col-span-1"><p className="text-sm text-slate-500">Alamat</p><p className="font-semibold mt-1">{data.partner.alamat||'-'}</p></div></div><h3 className="text-lg font-bold mb-3">Riwayat Pesanan</h3><div className="space-y-3">{data.orders.length===0&&<div className="bg-white border rounded-2xl p-8 text-center text-slate-500">Belum ada pesanan.</div>}{data.orders.map(o=>{const Icon=statusIcon[o.status]||Package;return <div key={o.id} className="bg-white border rounded-2xl p-5 flex items-start justify-between gap-4"><div><p className="font-bold">{new Date(o.createdAt).toLocaleDateString('id-ID',{day:'2-digit',month:'long',year:'numeric'})}</p><p className="text-sm text-slate-500 mt-1">{o.orderItems.length} produk • {rupiah(o.totalHarga)}</p><p className="text-xs text-slate-400 mt-1">Order #{o.id.slice(-8).toUpperCase()}</p></div><span className="capitalize rounded-full bg-slate-100 px-3 py-2 text-sm font-semibold flex gap-2 items-center"><Icon size={16}/>{o.status}</span></div>})}</div></div></main>
}
